name: Run Tests

on:
  push:
    branches: [ main, ali2 ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Run tests
      run: npm test
      
    - name: Upload coverage reports
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage/
        
    - name: Test Status Check
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "All tests passed!"
          exit 0
        else
          echo "Tests failed!"
          exit 1
        fi